# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Kieran R Campbell'
tagline:             'Research blog'
description:         'A blog on computational genomics, statistics and coding. Oxford, UK.'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Kieran Campbell
  url:               https://twitter.com/kieranrcampbell
  email:             kieranrcampbell@gmail.com

# Custom vars
version:             1.0.0
